name: ednet_core_default_app
version: 1.0.3
description: ednet core default app is used to interpret a EDNetCore model and provide a web app to navigate through the model starting by its entry points
homepage: https://github.com/ednet-dev/ednet_core_default_app
documentation: http://goo.gl/Fd08zZ

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:

  ednet_core:
    path: ../../packages/core
  yaml: ^3.1.2


  intl: ^0.18.1
