name: ednet_core_default_app
version: 1.0.3
description: ednet core default app is used to interpret a EDNetCore model and provide a web app to navigate through the model starting by its entry points
homepage: https://github.com/ednet-dev/ednet_core_default_app
documentation: http://goo.gl/Fd08zZ

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  test: 1.22.0

  ednet_core:
    path: ../../../cms/packages/core

  intl:  ^0.17.0
